### ISSUE TITLE
[BUG] Reporting behind Reverse Proxy doesn't work

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#16]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

---
I can't generate any reports and I believe it has to do with the reverse Proxy setting. The headless chrome that launches isn't communicating back through the proxy port and or path. There doesn't seem to be a setting specific to the kibana report like there is for the main kibana setting from elasticsearch.

Is there a method to get this to work right now on a reverse proxy?

Thanks!

This issue was submitted by @ky-ma
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/332

**Comment by ky-ma** [comment]
Update:

Go do Discover
Create A filter, save the filter
click reporting
generate CSV

Expected Behavior
a dialog box that allows you to save the CSV file

Plugins
The standard plugs

It's the reverse proxy of exposing the Kibana UI through a "path" that's the problem when launching the headless chrome to create the CSV file.

**Comment by zhongnansu** [comment]
https://github.com/opensearch-project/dashboards-reports/pull/222 
This PR introduces some reporting specific settings that can be used to address this issue. It's availabe in 1.2 onwards.
