### ISSUE TITLE
[BUG]Negative values not exported correctly

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

---

Issue occurred when generating CSV file from a table in Discover. Negative numbers appear in the csv with an extra `'` in front of them. This is what it looks like:

Negative value | Positive value
-- | --
'-47 | 520
'-15 | 475

For reference, this field is of type `number`

This issue is submitted by @melvinkokxw
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/344

**Comment by MKCG** [comment]
The reason seems to be related to how Microsoft Excel handles CSV files : https://github.com/opensearch-project/dashboards-reports/blob/main/dashboards-reports/server/routes/utils/dataReportHelpers.ts#L235

I understand that it is meant to prevent any injection but I don't think that any exported content should be modified for any reason.
